### ISSUE TITLE
404 -- Unknown POST type when connecting google docs add on to WP blog

### ISSUE THREAD

**Issue by jeff-vincent** [Automattic/google-docs-add-on#115]
I'm using a Chromebook and trying to connect to a WP blog. When I click "Add Wordpress Site"; select my blog from the dropdown list; and click "Approve" ...

I get this error as html in my browser: 

```
Request failed for https://public-api.wordpress.com/rest/v1.1/sites/148624828/post-types/page/taxonomies returned code 404. Truncated server response: {"error":"unknown_post_type","message":"Unknown post type"} (use muteHttpExceptions option to examine full response)
```

**Comment by douglas-johnson** [comment]
I am experiencing a very similar issue. It might be the exact same problem so I'm adding on to this issue instead of making a new one.

Here is a screenshot of the error I receive once the OAuth process redirects me back to Google Docs.

<img width="1420" alt="Screen Shot 2020-08-11 at 12 38 14 PM" src="https://user-images.githubusercontent.com/226381/94047980-d2b6a000-fda0-11ea-8bc4-8ebfda9190a6.png">

I've also provided video of the OAuth process to VIP support in this Zendesk issue: https://wordpressvip.zendesk.com/hc/en-us/requests/114155

**Comment by mikeyarce** [comment]
@georgeh - as @douglas-johnson is showing, we have this issue on VIP Go right now.   
Here's what is happening:

- When a custom post type returns as ``"publicly_queryable" => false`, the connection will fail.   On VIP Go, it looks like for some reason the post_types of: `page, block, feedback, product` are what's causing the issue.   
- Here's the conditional that fails:  https://github.com/Automattic/jetpack/blob/eeb7243b4c0fff6019324a2271ce3a5426ddb176/json-endpoints/class.wpcom-json-api-list-post-type-taxonomies-endpoint.php#L47-L50

Can we limit this to just `posts` somehow?

**Comment by georgeh** [comment]
@mikeyarce it looks like that the taxonomies query that is blowing up, so I am skipping post_types where `publicly_queryable === false` in #120: https://github.com/Automattic/google-docs-add-on/pull/120/commits/4072a3d934055a20c401c72e0edbea9f722fc7c1

Once I have a testable version posted somewhere can I get you to test it?

**Comment by mikeyarce** [comment]
> Once I have a testable version posted somewhere can I get you to test it?

Absolutely, @georgeh !
