### ISSUE TITLE
reopen of unable to connect Google Docs

### ISSUE THREAD

**Issue by BoDonkey** [Automattic/google-docs-add-on#34]
Hi, 
I had tagged onto another persons issue. Bad me! Anyway, I can't connect my Google Docs to the site http://www.robertmeans.net. At first it was that I didn't have the API on. Now that the API is on I get the error message that the site does not seem to be accessible or no longer has jetpack installed. Both of which are not true. I went through the troubleshooting tips and my xmlrpc.php is correct. Any other ideas?
Thanks,
Bob

**Comment by johngodley** [comment]
I had this problem occur with my own Jetpack site. Adding a screenshot here for reference:

<img width="543" alt="authorize_wordpress_com_for_google_docs" src="https://cloud.githubusercontent.com/assets/1277682/23849503/be81f736-07d3-11e7-9f32-53d6c3e1455d.png">

I clicked Approve a second time and it worked.

Have you tried approving it again @BoDonkey ? We'll try and track down the underlying problem.

**Comment by georgeh** [comment]
@BoDonkey I took a look and your site on the WordPress API and everything looks like it should have connected.

That error happens when we try to confirm that your site still has the Jetpack plugin still installed. From a technical perspective, we send an XML-RPC request to your site for `jetpack.testConnection` in order to make sure that your site is connected. I ran some tests on your site and everything looks right.

Have you tried disabling all plugins except Jetpack?
