### ISSUE TITLE
How can multiple people export to the same wordpress.org site?

### ISSUE THREAD

**Issue by harrism** [Automattic/google-docs-add-on#82]
I can't find any way for multiple users to export to the same wordpress.org site, if only one user has the Jetpack connection account for the site. We collaborate on posts and have multiple editors who need to export.

**Comment by georgeh** [comment]
I think I understand what you're describing, but let me be sure. On your WordPress.org site you have User A and User B. User A has connected their Jetpack account to the site, but User B has not. What you would like is for User B to be able to use the add-on to create their posts on the WordPress.org site, using User A's Jetpack connection?

Is there reason why User B does not want to have their own Jetpack connection?

**Comment by harrism** [comment]
I thought I could only connect my blog to a single Jetpack account. What would that do to stats reporting if multiple users try to connect it? Also, ideally, I wouldn't require all my colleagues to have to create a Wordpress.com account -- they already have to have an account on the blog, and on Google, etc. It would be nice for the add-on to use their login on our wordpress.org blog for exporting...

**Comment by georgeh** [comment]
Each user that logs into the WordPress.org site should have the option to connect to Jetpack with their WordPress.com login. That will link their .org account to their .com account, but won't change the site's owner in Jetpack. (To get a little technical, the "master user" in Jetpack is the one who originally connected the site, everyone else is a regular user). The site stats will stay linked to the site and should just work. If you run into problems with the stats, you can [contact Jetpack support](https://jetpack.com/support/wordpress-com-stats/missing-stats/) and they can get things fixed.

I can appreciate not wanting to force everyone to have a WordPress.org, Google, and WordPress.com account. I've explored using the REST Content APIs to allow us to talk directly to WordPress.org sites, but without any sort of authentication system we are either forced to store users' passwords or force folks to use an Oauth plugin. The WordPress.com API has been the best solution to authentication we could come up with.

I do want to make sure you're aware that it's possible to force WordPress.org users to log in with a WordPress.com account using [Jetpack's SSO features](https://jetpack.com/support/sso/). Obviously that would need to fit in with your org's larger goals in order to make sense, but if it does work for you then you could get the 3 logins down to 2.

I'm going to mark this issue as closed but if you run into any issues with multiple Jetpack users feel free to re-open or create a new issue.
